dtb/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt

from . import views
from deal_search import views as deal_search_views

urlpatterns = [
    path('tgadmin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', views.index, name="index"),
    path('super_secter_webhook/', csrf_exempt(views.TelegramBotWebhookView.as_view())),
    path('deals/<str:provider>', deal_search_views.index, name='deals_index')
]

deal_search/models.py
from django.db import models
from users.models import User
from tgbot.handlers.broadcast_message.utils import send_one_message
import deal_search.modules.deals_client.client as client
from tgbot.handlers.deal_search import static_text

class Provider(models.Model):
    identifier = models.CharField(max_length=10)

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    product_id = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    search_type = models.CharField(max_length=10)

    def fetch_items_and_notify(self):
        postings = self._fetch_postings()

        new_postings = self._find_new_postings(postings)

        ## Send telegram notification
        if len(postings) > 0:
            for posting in new_postings:
                text = static_text.result.format(name=posting.name, price=posting.price, branch_name=posting.outlet_name, url=posting.fundgrube_url())
                send_one_message(text=text, user_id=self.user.user_id, disable_web_page_preview=True)
                
                ## Store new found posting_ids    
                IndexedPosting.objects.create(notification=self, posting_id=posting.id)
    
    @classmethod
    def fetch_items_and_notify_all(cls):
        for notification in cls.objects.all():
            notification.fetch_items_and_notify()
    
    def _fetch_postings(self):
        provider = client.Provider(self.provider)

        branch_ids = ','.join([str(branch_selection.branch.branch_id) for branch_selection in BranchSelection.objects.filter(user=self.user).select_related('branch')])

        query_params = {"text": self.product_id, "outletIds": branch_ids}
        query = client.DealsQuery(query_params)
        search = client.DealSearch(provider, query)
        postings = search.postings()

        return postings

    def _find_new_postings(self, postings):
        indexed_posting_ids = self.indexedposting_set.values_list('posting_id', flat=True)

        return [posting for posting in postings if posting.id not in indexed_posting_ids]

class Branch(models.Model):
    name = models.CharField(max_length=255)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    branch_id = models.IntegerField()
    zip_code = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    @classmethod
    def sync_remote(cls, provider):
        c_provider = client.Provider(provider.identifier)
        search = client.BranchSearch(provider = c_provider, limit=1000)
        c_branches = search.fetch_branches()

        for branch in c_branches:
            Branch.objects.get_or_create(
                name = branch['displayNameShort'],
                provider = provider,
                branch_id = branch['id'],
                zip_code = branch['address']['zipCode']
            )
        
    class Meta:
        ordering = ["zip_code"]

class BranchSelection(models.Model):
    user =  models.ForeignKey(User, on_delete=models.CASCADE)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

class IndexedPosting(models.Model):
    notification = models.ForeignKey(Notification, on_delete=models.CASCADE)
    posting_id = models.CharField(max_length=255)

class Posting(models.Model): 
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    posting_id = models.CharField(max_length=36)
    product_id = models.IntegerField()
    price = models.DecimalField(decimal_places=2,max_digits=8)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    image_url = models.TextField()
    shipping_type = models.CharField(max_length=255)
    shipping_cost = models.DecimalField(decimal_places=2,max_digits=6)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    shop_url = models.CharField(max_length=255)

    class Meta:
        ordering = ["price"]

    @classmethod
    def sync_remote_by_branch(cls, provider, branch):
        c_provider = client.Provider(provider.identifier)
        c_query = client.DealsQuery({"outletIds": branch.branch_id})
        c_search = client.DealSearch(c_provider, c_query)

        c_postings = c_search.postings()

        known_posting_ids = [posting.posting_id for posting in Posting.objects.filter(provider=provider, branch=branch).only('posting_id')]

        created_count = 0
        for c_posting in c_postings:
            if c_posting.id in known_posting_ids:
                continue
            else:
                Posting.objects.create(
                    provider = provider,
                    name = c_posting.name,
                    description = c_posting.text,
                    posting_id = c_posting.id,
                    product_id = c_posting.pim_id,
                    price = c_posting.price,
                    branch = branch,
                    image_url = c_posting.original_url,
                    shipping_type = c_posting.shipping_type,
                    shipping_cost = c_posting.shipping_cost,
                    shop_url = c_posting.fundgrube_url()
                )

                created_count += 1
        
        print(f"Branch {branch.branch_id}: Created {created_count} postings.")

    @classmethod
    def sync_remote(cls):
        for branch in Branch.objects.all():
            cls.sync_remote_by_branch(branch.provider, branch)

deal_search/views.py
from django.shortcuts import render, redirect, get_object_or_404
from deal_search.models import Provider
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

def index(request, provider):   
    PROVIDERS = {
        "mediamarkt": "MM",
        "saturn": "SAT"
    }
 
    city = str(request.GET.get('city') or "")
    identifier = PROVIDERS.get(provider)
    provider_query = get_object_or_404(Provider, identifier=identifier)
    branches_query = provider_query.branch_set
    paginator = Paginator(branches_query.filter(name__icontains=city), 20)
    page = request.GET.get('page') or 1
    
    try:
      paginated_branches = paginator.page(page)
    except (PageNotAnInteger, EmptyPage):
      return redirect("deals_index", provider=provider)   
    
    return render(
      request,
      "deals/index.html",
      {
          "branches": paginated_branches,
          "provider": provider
      } 
    )

deal_search/templates/deals/index.html
{% load django_bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

<div class="container-md">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/deals/{{provider}}">{{provider|title}} Fundgrube</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <form class="d-flex mt-2" role="search" action="/deals/{{provider}}">
          <input class="form-control me-2" type="search" placeholder="Search by City" aria-label="Search" name="city">
          <button class="btn btn-primary" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  {% for branch in branches %}
    <div class="accordion" id="branch-{{branch.branch_id}}">
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#postings-branch-{{branch.branch_id}}" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
            <span class="badge bg-primary rounded-pill me-2">{{ branch.posting_set.count }}</span> {{ branch.zip_code }} - {{ branch.name }} 
          </button>
        </h2>
        <div id="postings-branch-{{branch.branch_id}}" class="accordion-collapse collapse">
          <div class="accordion-body">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Price</th>
                  <th scope="col">Shipping</th>
                  <th scope="col">Shipping Cost</th>
                </tr>
              </thead>
              <tbody>
                {% for posting in branch.posting_set.all %}
                  <tr>
                    <th scope="row"><a href={{posting.shop_url}} target="_blank">{{ posting.name|truncatechars:120 }}</a></th>
                    <td>{{ posting.price }} €</td>
                    <td>{{ posting.shipping_type }}</td>
                    <td>{{ posting.shipping_cost }}</td>
                  </tr>
                {% endfor %}
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

  {% if branches.has_other_pages %}
    <nav aria-label="Page navigation example">
      <ul class="pagination mt-4 position-absolute start-50 translate-middle">
        {% if branches.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ branches.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% endif %}

        {% for page_number in branches.paginator.page_range %}
          {% if branches.number == page_number %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
          {% endif %}
        {% endfor %}

        {% if branches.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ branches.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
</div>